#!/bin/bash

export DESKTOP_CORE_NAME="teamviewer"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=latest
export DESKTOP_CORE_ORG="teamviewer"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/teamviewer/releases/download"
